DROP TABLE IF EXISTS Inspirations;

CREATE TABLE Inspirations (
    id INTEGER AUTOINCREMENT,
    quote TEXT NOT NULL
);

--INSERT INTO Inspirations (quote) VALUES
--('All our dreams can come true, if we have the courage to pursue them. —Walt Disney'),
--('The secret of getting ahead is getting started. —Mark Twain'),
--("I’ve missed more than 9,000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life, and that is why I succeed. —Michael Jordan"),
--("You’ve gotta dance like there’s nobody watching, love like you’ll never be hurt, sing like there’s nobody listening, and live like it’s heaven on earth. —William W. Purkey"),
--("Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.―Neil Gaiman"),
--("Everything you can imagine is real.―Pablo Picasso"),
--("When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us. ―Helen Keller"),
--("Do one thing every day that scares you. ―Eleanor Roosevelt"),
--("It’s no use going back to yesterday, because I was a different person then. ―Lewis Carroll"),
--("Smart people learn from everything and everyone, average people from their experiences, stupid people already have all the answers. —Socrates"),
--("Do what you feel in your heart to be right―for you’ll be criticized anyway. ―Eleanor Roosevelt"),
--("Happiness is not something ready made. It comes from your own actions. ―Dalai Lama XIV"),
--("Whatever you are, be a good one. ―Abraham Lincoln"),
--("If we have the attitude that it’s going to be a great day it usually is. —Catherine Pulsifier"),
--("Impossible is just an opinion. —Paulo Coelho"),
--("Your passion is waiting for your courage to catch up. —Isabelle Lafleche"),
--("Don’t be afraid to give up the good to go for the great. —John D. Rockefeller"),
--("No one is to blame for your future situation but yourself. If you want to be successful, then become ‘Successful.’ ―Jaymin Shah"),
--("Things may come to those who wait, but only the things left by those who hustle. ―Abraham Lincoln"),
--("Everything comes to him who hustles while he waits. ―Thomas Edison"),
--("Greatness only comes before hustle in the dictionary. ―Ross Simmonds"),
--("Great things are done by a series of small things brought together. ―Vincent Van Gogh"),
--("Very often, a change of self is needed more than a change of scene. ―A.C. Benson"),
--("The hard days are what make you stronger. ―Aly Raisman"),
--("If you believe it’ll work out, you’ll see opportunities. If you don’t believe it’ll work out, you’ll see obstacles. ―Wayne Dyer"),
--("Keep your eyes on the stars, and your feet on the ground. ―Theodore Roosevelt"),
--("You can waste your lives drawing lines. Or you can live your life crossing them. ―Shonda Rhimes"),
--("I now tried a new hypothesis: It was possible that I was more in charge of my happiness than I was allowing myself to be. ―Michelle Obama"),
--("Work hard in silence, let your success be the noise. ―Frank Ocean"),
--("If opportunity doesn’t knock, build a door. ―Kurt Cobain"),
--("Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. ―Roy T. Bennett"),
--("Everyone has inside them a piece of good news. The good news is you don’t know how great you can be! How much you can love! What you can accomplish! And what your potential is. ―Anne Frank"),
--("Good. Better. Best. Never let it rest. ’Til your good is better and your better is best. ―St. Jerome."),
--("In the middle of every difficulty lies opportunity. ―Albert Einstein"),
--("Start where you are. Use what you have. Do what you can. ―Arthur Ashe"),
--("Dreams don’t work unless you do. ―John C. Maxwell"),
--("Go the extra mile. It’s never crowded there. ―Dr. Wayne D. Dyer"),
--("Keep your face always toward the sunshine―and shadows will fall behind you. ―Walt Whitman"),
--("Make each day your masterpiece. ―John Wooden"),
--("Wherever you go, go with all your heart. ―Confucius"),
--("Turn your wounds into wisdom. ―Oprah Winfrey"),
--("We can do anything we want to if we stick to it long enough. ―Helen Keller"),
--("Every champion was once a contender that didn’t give up. ―Gabby Douglas"),
--("Success is liking yourself, liking what you do, and liking how you do it. ―Maya Angelou"),
--("If you obey all the rules, you miss all the fun. ―Katharine Hepburn"),
--("You were born to be a player. You were meant to be here. This moment is yours. ―Herb Brooks"),
--("When you reach the end of your rope, tie a knot and hang out. ―Abraham Lincoln"),
--("You must do the thing you think you cannot do. ―Eleanor Roosevelt"),
--("Never regret anything that made you smile. ―Mark Twain"),
--("I never lose. Either I win or learn. ―Nelson Mandela");